### ISSUE TITLE
error when use it

### ISSUE THREAD

**Issue by laurivers** [IGRSoft/libpng-xcode-project#1]
I build framework success,but when other project use that framework, will has a error "pnglibconf.h file not found".

**Comment by ikorich** [comment]
ok,
I'll add example to check that in few days

**Comment by nicoraf** [comment]
Hi, I could include your project with libpgn 1.6.16 files from the offical website.
I had linking problems when I use that project in another XCode.
I drag and drop your project with libpgn files and the build both projects.

For instance, 
I have a linking problem when I use "png_destroy_read_struct" function.

Undefined symbols for architecture arm64:
  "_inflateEnd", referenced from:
      _png_read_destroy in libpng.a(pngread.o)
ld: symbol(s) not found for architecture arm64

**Comment by nicoraf** [comment]
The root cause is that libpng library depends of zlib library. I worked for me creating another similar project for zlib, then make yours depend to that XCode project.

**Comment by nicoraf** [comment]
I think that you should also include an XCode project that has zlib and make this libpng project depend on it.

**Comment by ikorich** [comment]
You should add zlib to your project
